# CodeRabbit AI 리뷰 설정
# https://docs.coderabbit.ai/guides/configure-coderabbit

# 리뷰 언어 설정
language: ko

# 리뷰 활성화
reviews:
  # 자동 리뷰 활성화
  auto_review:
    enabled: true
    # draft PR도 리뷰
    drafts: false
    # 자동 리뷰할 base 브랜치 설정
    base_branches:
      - develop
      - main

  # 리뷰 범위
  scope:
    # 모든 파일 리뷰
    include:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
    # 제외할 파일
    exclude:
      - 'node_modules/**'
      - 'dist/**'
      - 'build/**'
      - '.next/**'
      - 'pnpm-lock.yaml'
      - 'package-lock.json'

  # 리뷰 상세 설정
  profile: 'assertive' # chill, assertive

  # 중요도 필터 (선택)
  # level: "notice" # info, notice, warning, error

# 자동 요약
summary:
  enabled: true

# 시 리뷰 (재미있는 시로 요약)
poem:
  enabled: false

# 워크플로우 설정
workflow:
  # PR 생성 시 자동 리뷰
  on_pr_open: true
  # PR 업데이트 시 자동 리뷰
  on_pr_update: true
  # 리뷰 요청 시 자동 리뷰
  on_review_request: true

# 코멘트 설정
comments:
  # 인라인 코멘트 활성화
  inline: true
  # 요약 코멘트 활성화
  summary: true

# 학습 설정 (프로젝트 컨텍스트)
knowledge_base:
  # 프로젝트 문서 참조
  documents:
    - 'CLAUDE.md'
    - 'README.md'
  # 코딩 스타일 가이드
  style_guides:
    - path: 'CLAUDE.md'
      description: 'FSD 아키텍처 및 코딩 규칙'

# 보안 스캔
security:
  enabled: true

# 성능 분석
performance:
  enabled: true

# 테스트 커버리지
tests:
  enabled: true
